// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5smaXCyOLAMz2TS4iNCL0QnAlfEMLKX8',
    appId: '1:741730777378:web:44baf38f748dda91904d7b',
    messagingSenderId: '741730777378',
    projectId: 'pruebatecnica-bfc8a',
    authDomain: 'pruebatecnica-bfc8a.firebaseapp.com',
    storageBucket: 'pruebatecnica-bfc8a.appspot.com',
    measurementId: 'G-17QMEPT7TC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnQcFuRco0o1D9Vzv0f64jMaC0CzvdRXc',
    appId: '1:741730777378:android:66b7b60563c35a6b904d7b',
    messagingSenderId: '741730777378',
    projectId: 'pruebatecnica-bfc8a',
    storageBucket: 'pruebatecnica-bfc8a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjxRgarPb8quUSi9eIlHxq_ju2cOT_Ub8',
    appId: '1:741730777378:ios:98d3b5d97f6d2c5f904d7b',
    messagingSenderId: '741730777378',
    projectId: 'pruebatecnica-bfc8a',
    storageBucket: 'pruebatecnica-bfc8a.appspot.com',
    androidClientId: '741730777378-vist98amuuv72uprn1vsbjh7kvj2rdk1.apps.googleusercontent.com',
    iosClientId: '741730777378-iierl3ai9etoa4r5stabi6nut7forjgm.apps.googleusercontent.com',
    iosBundleId: 'com.example.loguinprueba',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjxRgarPb8quUSi9eIlHxq_ju2cOT_Ub8',
    appId: '1:741730777378:ios:7c7a871c65b5ae84904d7b',
    messagingSenderId: '741730777378',
    projectId: 'pruebatecnica-bfc8a',
    storageBucket: 'pruebatecnica-bfc8a.appspot.com',
    androidClientId: '741730777378-vist98amuuv72uprn1vsbjh7kvj2rdk1.apps.googleusercontent.com',
    iosClientId: '741730777378-j1tqoanr856j5mv25knmpov3mq7dbt1p.apps.googleusercontent.com',
    iosBundleId: 'com.example.loguinprueba.RunnerTests',
  );
}
